/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface ArLauncher {
    }
    interface ArLocation {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLArLauncherElement extends Components.ArLauncher, HTMLStencilElement {
    }
    var HTMLArLauncherElement: {
        prototype: HTMLArLauncherElement;
        new (): HTMLArLauncherElement;
    };
    interface HTMLArLocationElement extends Components.ArLocation, HTMLStencilElement {
    }
    var HTMLArLocationElement: {
        prototype: HTMLArLocationElement;
        new (): HTMLArLocationElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "ar-launcher": HTMLArLauncherElement;
        "ar-location": HTMLArLocationElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface ArLauncher {
    }
    interface ArLocation {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "ar-launcher": ArLauncher;
        "ar-location": ArLocation;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "ar-launcher": LocalJSX.ArLauncher & JSXBase.HTMLAttributes<HTMLArLauncherElement>;
            "ar-location": LocalJSX.ArLocation & JSXBase.HTMLAttributes<HTMLArLocationElement>;
        }
    }
}
